dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

env:
  global:
    - CC_TEST_REPORTER_ID=acb0a765dd2f1e01f61ff0a206bcef6ca0f9a2a02cb979941edf9c11a5988ffb
    - NODE_ENV=test

cache:
  directories:
    - ./node_modules

before_install:
  - mysql -e 'CREATE DATABASE cats;'

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
#  - npx ts-node src/load-fixtures.ts

script:
  - npm run test:cov

after_script:
  - mkdir coverage
  - mv test/coverage/lcov.info coverage/lcov.info
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
  - npx coveralls <./coverage/lcov.info
